package io.github.opencubicchunks.cubicchunks.api;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

import javax.annotation.Nullable;

import io.github.opencubicchunks.cubicchunks.CanBeCubic;
import io.github.opencubicchunks.cubicchunks.CubicChunks;
import io.github.opencubicchunks.cubicchunks.world.level.CubicHeight;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.chunk.status.ChunkStatus;

/**
 * What other mods use of Cubic Chunks: whether a level is cubic and the heights its world holds, and how to generate the terrain of a cubic
 * level's cubes. Everything in this package is the public API (kept in its own jar to compile against: ./gradlew apiJar); the rest of Cubic
 * Chunks may change at any time.
 */
public final class CubicApi {
    private static final Map<Class<? extends ChunkGenerator>, CubeGenerator.Factory> FACTORIES = new ConcurrentHashMap<>();
    private static final Map<ServerLevel, CubeGenerator> GENERATORS = new ConcurrentHashMap<>();
    /** A level whose chunk generator has no cube generator (kept so the factories are asked once). */
    private static final CubeGenerator NONE = cube -> {
        throw new IllegalStateException("no cube generator");
    };

    private CubicApi() {
    }

    /** Whether the level is cubic (its world was made with Cubic Chunks on). */
    public static boolean isCubic(Level level) {
        return ((CanBeCubic) level).cc_isCubic();
    }

    /** The lowest Y a cubic level's world holds (a level that is not cubic: its dimension's). */
    public static int minY(Level level) {
        return CubicHeight.minY(level);
    }

    /** The highest Y a cubic level's world holds (a level that is not cubic: its dimension's). */
    public static int maxY(Level level) {
        return CubicHeight.maxY(level);
    }

    /**
     * Makes cubic levels whose chunk generator is of this class (or a subclass) generate their cubes' terrain with the factory's cube
     * generator instead of Cubic Chunks' own placeholder terrain. Register at startup (a mod initializer).
     */
    public static void registerCubeGenerator(Class<? extends ChunkGenerator> chunkGeneratorClass, CubeGenerator.Factory factory) {
        FACTORIES.put(chunkGeneratorClass, factory);
        CubicChunks.LOGGER.info("Cubic levels generated by {} get their cubes from {}", chunkGeneratorClass.getName(), factory.getClass().getName());
    }

    /** The cube generator of a cubic level, or null if its chunk generator has none (Cubic Chunks' placeholder terrain then). */
    public static @Nullable CubeGenerator cubeGenerator(ServerLevel level) {
        CubeGenerator generator = GENERATORS.computeIfAbsent(level, CubicApi::create);
        return generator == NONE ? null : generator;
    }

    private static CubeGenerator create(ServerLevel level) {
        ChunkGenerator chunkGenerator = level.getChunkSource().getGenerator();
        for (Class<?> type = chunkGenerator.getClass(); type != null && ChunkGenerator.class.isAssignableFrom(type); type = type.getSuperclass()) {
            CubeGenerator.Factory factory = FACTORIES.get(type);
            if (factory != null) {
                CubeGenerator generator = factory.create(level, chunkGenerator);
                if (generator != null) {
                    return generator;
                }
            }
        }
        return NONE;
    }

    /** Whether the level's cube generator places vanilla structures (see {@link CubeGenerator#usesStructures}). */
    public static boolean usesStructures(ServerLevel level) {
        CubeGenerator generator = cubeGenerator(level);
        return generator != null && generator.usesStructures();
    }

    /**
     * A column of a cubic level if it has reached the status, or null; from any thread, never waiting or loading. A cubic level's columns
     * hold what vanilla keeps per chunk for structures (their starts and references, see {@link CubeGenerator#usesStructures}); its cubes
     * hold the blocks. While a cube is being decorated, the columns within ten chunks of it have their structure starts, and those within two
     * their references, as vanilla's chunks have theirs while a chunk is decorated.
     */
    public static @Nullable ChunkAccess column(ServerLevel level, int chunkX, int chunkZ, ChunkStatus status) {
        return ((io.github.opencubicchunks.cubicchunks.server.level.ServerCubeCache) level.getChunkSource()).cc_getColumnNow(chunkX, chunkZ, status);
    }

    /** Told about the cubes of cubic server levels joining and leaving the level (on the server thread). */
    public interface CubeListener {
        /** The cube has become full: its blocks can be read (with Level.getBlockState and the like). */
        void onCubeLoaded(ServerLevel level, int cubeX, int cubeY, int cubeZ);

        /** The cube is no longer full (it is being unloaded); blocks changed in it since it loaded are still there to read. */
        default void onCubeUnloaded(ServerLevel level, int cubeX, int cubeY, int cubeZ) {
        }
    }

    private static final List<CubeListener> LISTENERS = new CopyOnWriteArrayList<>();

    /** Adds a listener for cubes loading and unloading in cubic server levels (at startup). */
    public static void addCubeListener(CubeListener listener) {
        LISTENERS.add(listener);
    }

    /** Cubic Chunks calls this as a cube becomes full (loaded) or stops being so (unloaded). */
    public static void fireCube(ServerLevel level, int cubeX, int cubeY, int cubeZ, boolean loaded) {
        for (CubeListener listener : LISTENERS) {
            try {
                if (loaded) {
                    listener.onCubeLoaded(level, cubeX, cubeY, cubeZ);
                } else {
                    listener.onCubeUnloaded(level, cubeX, cubeY, cubeZ);
                }
            } catch (RuntimeException e) {
                CubicChunks.LOGGER.error("Cube listener {} failed", listener, e);
            }
        }
    }

    /** Whether the cube is loaded and full (from any thread, never waiting). */
    public static boolean isCubeLoaded(ServerLevel level, int cubeX, int cubeY, int cubeZ) {
        return ((io.github.opencubicchunks.cubicchunks.server.level.ServerCubeCache) level.getChunkSource())
                .cc_getFullCubeNow(io.github.opencubicchunks.cc_core.api.CubePos.of(cubeX, cubeY, cubeZ)) != null;
    }

    /** Whether the cube is loaded and holds nothing but air (from any thread, never waiting). */
    public static boolean isCubeEmpty(ServerLevel level, int cubeX, int cubeY, int cubeZ) {
        var cube = ((io.github.opencubicchunks.cubicchunks.server.level.ServerCubeCache) level.getChunkSource())
                .cc_getFullCubeNow(io.github.opencubicchunks.cc_core.api.CubePos.of(cubeX, cubeY, cubeZ));
        if (cube == null) {
            return false;
        }
        for (var section : cube.getSections()) {
            if (!section.hasOnlyAir()) {
                return false;
            }
        }
        return true;
    }

    /** A cube's blocks as {@link #readCube} found them. */
    public interface CubeBlocks {
        /** The block at a world position inside the cube. */
        net.minecraft.world.level.block.state.BlockState getBlock(int x, int y, int z);

        /** Whether the cube holds nothing but air. */
        boolean isEmpty();
    }

    /**
     * A cube's blocks once its terrain was generated (it may not be decorated yet): the cube in memory, full or still generating, else the
     * saved one; empty when there is neither. From any thread; reading a saved cube waits for the disk, so not on the server thread.
     */
    public static java.util.Optional<CubeBlocks> readCube(ServerLevel level, int cubeX, int cubeY, int cubeZ) {
        var pos = io.github.opencubicchunks.cc_core.api.CubePos.of(cubeX, cubeY, cubeZ);
        var loaded = ((io.github.opencubicchunks.cubicchunks.server.level.ServerCubeCache) level.getChunkSource()).cc_getCubeNow(pos, ChunkStatus.TERRAIN);
        net.minecraft.world.level.chunk.LevelChunkSection[] sections = null;
        if (loaded != null) {
            sections = loaded.getSections();
        } else {
            var saved = ((io.github.opencubicchunks.cubicchunks.server.level.CubicChunkMap) level.getChunkSource().chunkMap).cc_readSavedCube(pos).join();
            if (saved.isPresent()) {
                var parsed = io.github.opencubicchunks.cubicchunks.world.storage.CubeSerializer.parse(level.registryAccess(), saved.get());
                if (parsed != null && parsed.status().isOrAfter(ChunkStatus.TERRAIN)) {
                    sections = parsed.sections();
                }
            }
        }
        if (sections == null) {
            return java.util.Optional.empty();
        }
        var s = sections;
        return java.util.Optional.of(new CubeBlocks() {
            @Override public net.minecraft.world.level.block.state.BlockState getBlock(int x, int y, int z) {
                return s[io.github.opencubicchunks.cc_core.utils.Coords.blockToIndex(x, y, z)].getBlockState(x & 15, y & 15, z & 15);
            }

            @Override public boolean isEmpty() {
                for (var section : s) {
                    if (!section.hasOnlyAir()) {
                        return false;
                    }
                }
                return true;
            }
        });
    }

    /**
     * Has the cube loaded (generated if need be) and held as full by a ticket of the given type until {@link #releaseCube}: the future
     * completes on the server thread with whether it became full. Server thread only. The ticket type must load and never expire (as vanilla's
     * addTicketAndLoadWithRadius asks); a pre-generation sweep holds its cubes so.
     */
    public static java.util.concurrent.CompletableFuture<Boolean> loadCube(ServerLevel level, net.minecraft.server.level.TicketType type, int cubeX,
            int cubeY, int cubeZ) {
        var cache = (io.github.opencubicchunks.cubicchunks.server.level.ServerCubeCache) level.getChunkSource();
        cache.cc_addTicketWithRadius(type, io.github.opencubicchunks.cc_core.world.level.CloPos.cube(cubeX, cubeY, cubeZ), 0);
        return cache.cc_getCubeFutureNoWait(cubeX, cubeY, cubeZ, ChunkStatus.FULL, true).thenApply(result -> result.isSuccess());
    }

    /** Lets go of a cube held by {@link #loadCube} with the ticket type (server thread). */
    public static void releaseCube(ServerLevel level, net.minecraft.server.level.TicketType type, int cubeX, int cubeY, int cubeZ) {
        ((io.github.opencubicchunks.cubicchunks.server.level.ServerCubeCache) level.getChunkSource())
                .cc_removeTicketWithRadius(type, io.github.opencubicchunks.cc_core.world.level.CloPos.cube(cubeX, cubeY, cubeZ), 0);
    }

    /** Cube and column writes queued for the level's disk and not done yet (from any thread). */
    public static int pendingCubeWrites(ServerLevel level) {
        return ((io.github.opencubicchunks.cubicchunks.server.level.CubicChunkMap) level.getChunkSource().chunkMap).cc_pendingCubeWrites();
    }

    /** Forgets a level's cube generator as the level unloads (Cubic Chunks calls this). */
    public static void forgetLevel(ServerLevel level) {
        GENERATORS.remove(level);
    }
}
